#!/usr/bin/ruby -w
require 'rubygems'

def is_palindrome?(val)
  len = val.size
  center = len / 2
  center_index = val.size.odd? ? center : center-1
  val[0..center_index] == val[center..(val.size-1)].reverse
end

if ARGV.size != 1
  puts "Usage: palindrome (filename)"
else
  puts "IS PALINDROME: #{is_palindrome?(ARGV[0])}"
end
